language: node_js
node_js:
  - 8.15
before_install:
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)
  - which rsync || (apt-get update -y && apt-get install rsync -y)
  - eval $(ssh-agent -s)
  - echo "$PROD_SERVER_AUTH" | tr '|' '\n' | tr '#' ' ' | tr -d '\r' | ssh-add - > /dev/null 
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: script
    script:
      - rsync -azvh --delete --rsh="ssh -p $PROD_SERVER_PORT -o StrictHostKeyChecking=no" build/* $PROD_SERVER_USER@$PROD_SERVER_IP:/var/www/web-app-campathon
    on:
      branch: master
branches:
  only:
    - master
