language: node_js
node_js:
  - 8.15
before_install:
  - openssl aes-256-cbc -K $encrypted_fcc97e029ac9_key -iv $encrypted_fcc97e029ac9_iv -in quan-server.pem.enc -out quan-server.pem -d
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)
  - which rsync || (apt-get update -y && apt-get install rsync -y)
  - eval $(ssh-agent -s)
  - ssh-add quan-server.pem
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: script
    script:
      - rsync -azvh --delete --rsh="ssh -p $PROD_SERVER_PORT -o StrictHostKeyChecking=no" build/* $PROD_SERVER_USER@$PROD_SERVER_IP:/var/www/web-app-campathon
    on:
      branch: master
branches:
  only:
    - master
